services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urmis_dev
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/urmis_dev?schema=public
      NODE_ENV: development
      JWT_SECRET: supersecret
    ports:
      - '3000:3000'
      - '5000:5000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npx prisma generate && npm run backend:start"

volumes:
  db_data:
