export const layoutConfigByRole = {
  SYSTEM_ADMIN: {
    navbar: [
      'Global Search',
      'Dashboard',
      'Notifications',
      'Messages',
      'Quick Actions',
      'Platform Status',
      'System Tools',
      'Profile',
      'Preferences',
      'Help',
      'Logout',
    ],
    cards: [
      'Total Universities',
      'Active Universities',
      'Suspended Universities',
      'Trial Universities',
      'University Administrators',
      'Platform Users',
      'Students',
      'Staff',
      'Active Sessions',
      'API Status',
      'Server Uptime',
      'Security Alerts',
    ],
    charts: [
      'University Growth',
      'Platform User Distribution',
      'Subscription Growth',
      'Daily Logins',
      'Platform Usage',
      'Storage Usage',
      'API Requests',
      'Security Events',
    ],
    quickActions: [
      'Create University',
      'Create University Administrator',
      'Create Platform User',
      'Assign Roles',
      'Manage Subscriptions',
      'Platform Reports',
      'System Monitoring',
      'Security Center',
      'Backup Database',
      'Global Settings',
    ],
  },
  UNIVERSITY_ADMIN: {
    navbar: [
      'Search',
      'Dashboard',
      'Notifications',
      'Messages',
      'Academic Calendar',
      'Quick Actions',
      'Profile',
      'University Settings',
      'Logout',
    ],
    cards: [
      'Students',
      'Staff',
      'Faculties',
      'Departments',
      'Programmes',
      'Courses',
      'Pending Registrations',
      'Pending Results',
      'Published Results',
      'Academic Session',
      'Active Users',
      'Notifications',
    ],
    charts: [
      'Student Enrollment',
      'Department Distribution',
      'Course Registration',
      'Result Publication',
      'Student Performance',
      'Faculty Distribution',
    ],
    quickActions: [
      'Create Faculty',
      'Create Department',
      'Create Programme',
      'Create Course',
      'Create Staff',
      'Create Student',
      'Open Registration',
      'Generate Reports',
      'Manage Users',
      'University Settings',
    ],
  },
  DEAN: {
    navbar: ['Search', 'Dashboard', 'Notifications', 'Messages', 'Faculty Calendar', 'Profile', 'Logout'],
    cards: ['Departments', 'Lecturers', 'Students', 'Courses', 'Pending Results', 'Approved Results', 'Faculty Performance', 'Notifications'],
    charts: ['Department Performance', 'Result Approval Trend', 'Student Performance', 'Course Distribution'],
    quickActions: ['Approve Results', 'Faculty Reports', 'Department Statistics', 'Review Assessments'],
  },
  HOD: {
    navbar: ['Search', 'Dashboard', 'Notifications', 'Messages', 'Profile', 'Logout'],
    cards: ['Lecturers', 'Students', 'Courses', 'Assessments', 'Pending Results', 'Verified Results', 'Department Performance'],
    charts: ['Course Performance', 'Assessment Progress', 'Result Verification', 'Student Distribution'],
    quickActions: ['Assign Courses', 'Verify Results', 'Department Reports', 'Manage Lecturers'],
  },
  LECTURER: {
    navbar: ['Search', 'Dashboard', 'Notifications', 'Messages', 'Profile', 'Logout'],
    cards: ['Assigned Courses', 'Registered Students', 'Assessments', 'Submitted Results', 'Pending Results', 'Upcoming Classes'],
    charts: ['Assessment Completion', 'Score Distribution', 'Course Enrollment', 'Result Submission Progress'],
    quickActions: ['Enter Scores', 'Create Assessment', 'Submit Results', 'View Students'],
  },
  EXAM_OFFICER: {
    navbar: ['Search', 'Dashboard', 'Notifications', 'Messages', 'Profile', 'Logout'],
    cards: ['Pending Results', 'Verified Results', 'Published Results', 'Transcript Requests', 'Graduation Candidates', 'Academic Sessions'],
    charts: ['Result Publication', 'Transcript Requests', 'Graduation Progress', 'Department Result Status'],
    quickActions: ['Publish Results', 'Generate Transcripts', 'Process Corrections', 'Academic Reports'],
  },
  STUDENT: {
    navbar: ['Search', 'Dashboard', 'Notifications', 'Messages', 'Academic Calendar', 'Profile', 'Settings', 'Logout'],
    cards: ['Registered Courses', 'Current GPA', 'Current CGPA', 'Outstanding Registrations', 'Published Results', 'Academic Standing', 'Transcript Requests', 'Notifications'],
    charts: ['Semester GPA', 'CGPA Trend', 'Course Registration', 'Academic Performance'],
    quickActions: ['Register Courses', 'View Results', 'Request Transcript', 'Download Result Slip', 'Update Profile'],
  },
};

export function getLayoutConfig(role) {
  return layoutConfigByRole[role] || layoutConfigByRole.STUDENT;
}
